name: Update Citation Badge

on:
  schedule:
    - cron: '0 0 * * *'  # 每天自动更新一次
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Generate citation badge
        run: python .github/scripts/update_citations.py

      - name: Commit and Push
        env:
          PERSONAL_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO_NAME: ${{ github.repository }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git remote set-url origin https://x-access-token:${PERSONAL_TOKEN}@github.com/${REPO_NAME}.git
          
          git add citation-badge.svg
          git commit -m "Update citation badge" || echo "No changes"
          git push origin main
