name: Update Arxiv Citations

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-citations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      
      - name: Configure git
        run: |
          git config --global user.email "[email protected]"
          git config --global user.name "github-actions[bot]"
          # 改写 remote URL，使用 GITHUB_TOKEN 验证
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      
      - name: Update citation counts
        run: |
          python .github/scripts/update_arxiv_citations.py
      
      - name: Commit and push
        run: |
          git add arxiv_citations.json
          git commit -m "Update arxiv citation counts [skip ci]" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}




